[package]
name = "raw"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "raw"
path = "src/main.rs"

[lib]
name = "raw"
path = "src/lib.rs"


[dependencies]
reqwest = { version = "0.13.3", features = ["blocking"] }
walkdir = "2"
recursive_copy = "1.3.0"
indicatif = "0.18.4"
anyhow = "1.0"
compress-tools = "0.16.1"
flate2 = "1.1.9"
tar = "0.4.46"
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread", "macros"] }
goblin = "0.10.7"
sha2 = "0.11.0"
hex-literal = "1.1.0"
hex = "0.4.3"
git2 = { version = "0.21.0", features = ["https"] }
